### ISSUE TITLE
Discussion: Removal of `hadolint` step in `linter.yml`

### ISSUE THREAD

**Issue by mikenye** [fredclausen/docker-baseimage#17]
Hi All,

Do we need the `hadolint` job in `linter.yml` workflow? If a Dockerfile is changed, it should be linted via the `hadolint` job in `on_pr.yml`.

Likewise, we might not need the `markdownlint` and `yamllint` jobs in the `on_pr.yml` workflow, as these get linted via `linter.yml`.

The jobs seem to be running twice currently, here's a screenshot from a PR I'm drafting, where .MD, .yml and Dockerfiles were added/changed.

![image](https://user-images.githubusercontent.com/6915079/152091813-f0d673d1-eae8-4364-b2d7-9c4c872c1504.png)

![image](https://user-images.githubusercontent.com/6915079/152091835-bbde2a56-70e1-464c-a960-691f8580092d.png)

![image](https://user-images.githubusercontent.com/6915079/152091871-29e5bf5c-b994-4f5f-ad02-61a19791bd0f.png)

Not a big deal, but it may be confusing for contributors.

Cheers.

**Comment by fredclausen** [comment]
That makes total sense. I’m happy to make that change
